// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image10":return img`
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
.............................fffffffffff........................................
...........................fffffffffffffff..f...................................
.....................ffffffffdddddddddddfff.f...................................
..................fffffffffddddddddddddddfffff..................................
................ffff.ffffddddddddddddddddddfffff................................
................f.f.fffddddddddddddddddddddddffffffffff.........................
...............f.ffffdddddddddddddddddddddddddffff.....ff.......................
...............f.fffdddddddddddddddddddddddddddffff......f......................
...............ffffddddddddddddddddddddddddddddfffffff....f.....................
..............ffffddddddddddddddddddddddddddddddf.ff..ff..ff....................
............ff.ffddddddddddddddddddddfffffdddddddffff..f...f....................
...........f.fffddddfffffddddddddddddfef1fddddddddffff..ff.f....................
..........f.ffffddddf1fefddddddddddddfefffdddddddddf.ff...ff....................
..........f.fffdddddffeefddddddddddddfeeffddddddddddffff...f....................
..........fffffddddffeeefddddddddddddfffffddddddddddf.fff..fff..................
..........ffffdddddffffffddddddddddddddddddddddddddddf.fff..ff..................
..........ffffdddddddddddddddddddddddddddddddddddddddf..ffffff..................
..........ff.fdddddddddddddddddddddddddddddddddddddddf..f.ffffff................
.........fffffddddddddddddddddddfdffdddddddddddddddddf..fffffffff...............
........ff.fffddddddddddddddddddfdfddddddddddddddddddf.......fffff..............
.......fff.f.fddddddddddddddddddfdfddddddddddddddddddf.........ff...............
...fffffff.f.fdddddddddddddddddfddfddddddddddddddddddf.........f.f..............
.......ff.ff.fddddddddfffdddddffddfdddddddddfffddddddf..........f.ff............
...ffff.ff...fddddddddf2ffdddffddddfddddddddffdddddddf..........f..ff...........
...fffff.....fddddddddff2ffddddddddffdddddddffdddddddf..........ffff............
......ff.....fdddddddddf22ffddddddddddddddddffdddddddf..........................
.............fdddddddddf222fffddddddddddddddffdddddddf..........................
.............fdddddddddff2222fffdddddddddddfffdddddddf..........................
..............fdddddddddff22222fffdddddddff2ffddddddf...........................
..............fddddddddddffff22222ffffdff222fdddddddf........ff..f..............
......ff.......fddddddddddddfff222222fff222ffddddddf......fffff.ff..............
.....ffffff....fddddddddddddddfff2222222222fdddddddf....fffdfdffddf.............
.....fdffdff....fddddddddddddddddfffffffffffddddddf.....fdfffdfddff.............
....ffdfdffff...fdddddddddddddddddddddddddddddddddf.....fdfffffddf..............
...fdfdfffddf....fdddddddddddddddddddddddddddddddf......fdffffddfff.............
...fdfdfffdfff....fdddddddddddddddddddddddddddddf.......fddddfddfdff............
...fdfdddfffdf.....fdddddddddddddddddddddddddddf........fddddddddddf............
..ffffdddddddf......fdddddddddddddddddddddddddf..........fffdddddddf............
..fdfdddddddff.......ffdddddddddddddddddddddff............fdfdddffff............
..fdfddddffff..........ffdddddddddddddddddff.............fdddffff...............
..fffdddfdf..............ffdddddddddddddff..............fddddff.................
...fddddfddf...............fffffffffffff................fddddf..................
....ffffdddf..............fdddddddddddddf..............fddddf...................
.......fddddf.............fdddddddddddddf.............fddddf....................
........fddddf............fdddddddddddddf............fdddddf....................
.........fddddf..........fdddddddddddddddf..........fdddddf.....................
.........fddddf..........fdddddddddddddddf..........fddddf......................
..........fddddf.........fddddddddddddddddf........fdddddf......................
...........fddddf.......fdddddddddddddddddf.......fdddddf.......................
............fdddf.......fddddddddddddddddddf.....fdddddf........................
.............fdddf......fddddddddddddddddddf....fddddddf........................
.............fddddf....fddddddddddddddddddddf..fddddddf.........................
..............fddddf...fddddddddddddddddddddf..fdddddf..........................
...............fdddf..fddddddddddddddddddddddffddddddf..........................
................fdddf.fddddddddddddddddddddddfddddddf...........................
.................fdddffdddddddddddddddddddddddfddddf............................
.................fdddfddddddddddddddddddddddddfddddf............................
..................fddfdddddddddddddddddddddddddfddf.............................
...................fdfdddddddddddddddddddddddddfdf..............................
....................fddddddddddddddddddddddddddfdf..............................
....................fdddddddddddddddddddddddddddf...............................
....................fdddddddddddddddddddddddddddf...............................
...................fdddddddddddddddddddddddddddddf..............................
...................fdddddddddddddddddddddddddddddf..............................
...................fddddddddddddddddddddddddddddddf.............................
..................fdddddddddddddddddddddddddddddddf.............................
..................fddddddddddddddddddddddddddddddddf............................
..................fddddddddddddddddddddddddddddddddf............................
.................fddddddddddddddddddddddddddddddddddf...........................
.................fddddddddddddddddddddddddddddddddddf...........................
................fddddddddddddddddddddddddddddddddddddf..........................
................fddddddddddddddddddddddddddddddddddddf..........................
................fdddddddddddddddddddddddddddddddddddddf.........................
...............fddddddddddddddddddddddddddddddddddddddf.........................
...............fdddddddddddddddddddddddddddddddddddddddf........................
...............fdddddddddddddddddddfffffffffffffffffffff........................
..............fffffffffffffffffffff......fddf...................................
.....................fdf..................fddf..................................
.....................fdf..................fddf..................................
.....................fdf...................fddf.................................
....................fdf....................fdddf................................
....................fdf.....................fddf................................
...................fdf.......................fddf...............................
...................fdf.......................fddf...............................
...................fdf........................fddf..............................
..................fdf.........................fddf..............................
..................fdf..........................fddf.............................
..................fdf..........................fddf.............................
.................fdf............................fddf............................
.................fdf............................fddf............................
................fddf.............................fddf...........................
................fdf..............................fdddf..........................
................fdf...............................fddf..........................
...............fdf.................................fddf.........................
...............fdf.................................fddf.........................
..............fddf..................................fdffffffff..................
..............fdf...................................ffffddddff..................
..............fdf....................................fddddddf...................
........fffffffdf....................................ffdddddf...................
........fdddddfff.....................................fffffff...................
........fddddddf................................................................
........fddddddf................................................................
........fffffddf................................................................
............ffff................................................................
................................................................................
................................................................................
................................................................................
`;
            case "image12":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. f . . . . . . . . . . . . f . 
. . f . . . . . . . . . . f . . 
. . . f . . . . . . . . f . . . 
. . . . f . . . . . . f . . . . 
. . . . . f f f f f f . . . . . 
. . . . . . . 7 7 . . . . . . . 
. . . . . . . 7 7 . . . . . . . 
. . . . . . . 7 7 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image1":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. f . . . . . . . . . . . . f . 
. . f . . . . . . . . . . f . . 
. . . f . . . . . . . . f . . . 
. . . . f . . . . . . f . . . . 
. . . . . f f f f f f . . . . . 
. . . . . . . 5 5 . . . . . . . 
. . . . . . . 5 5 . . . . . . . 
. . . . . . . 5 5 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":return img`
111.........111..1...1.1111...11.........11................1
1..1........1..1.1...1.1...1.1..1.......1..1...............1
111...111...111..1...1.1...1.1..1.......1..1.......1.......1
1..1.1...1..1..1..111..1111...11..1......11..1...1...1.....1
1..1.1...1..1..1.....1.1.....1.....111.....1.1...1.1..111..1
1..1.1...1..1..1.....1.1.....1....1...1....1.1...1.1.1...1.1
1..1..111.1.1..1.....1.1......111.1...1....1..111..1.1...1..
111.........111..1111..1..........1...1.111..1.....1.1...1.1
`;
            case "image3":return img`
. . . . . 9 9 9 1 9 9 . . . . . 
. . . . 9 9 9 9 1 9 9 9 . . . . 
. . . 1 9 9 9 9 1 9 9 9 1 . . . 
. . 9 1 9 9 9 9 1 9 9 9 1 9 . . 
. 1 1 1 1 9 9 9 1 9 9 9 1 1 1 . 
. 9 9 1 1 9 9 9 1 9 9 1 1 9 9 . 
. 9 9 1 9 1 9 9 1 1 1 9 1 9 9 . 
. 9 9 1 9 9 1 1 1 9 9 9 1 9 9 . 
. 9 9 1 9 9 9 9 1 9 9 9 1 9 9 . 
. 9 9 1 9 9 9 9 1 9 9 9 1 9 9 . 
. . 9 1 9 9 9 9 1 9 9 9 1 9 . . 
. . . 1 9 9 9 9 1 9 9 9 1 . . . 
. . . . 9 9 9 9 1 9 9 9 . . . . 
. . . . . 9 9 9 1 9 9 . . . . . 
. . . . . . 9 9 1 9 . . . . . . 
. . . . . . . 9 1 . . . . . . . 
`;
            case "image4":return img`
. . . . . . . . . . . . . . . . 
. . . . d d f f f f d d . . . . 
. . . d d d d d d d d d d . . . 
. . . d d 1 1 1 d 1 1 1 d . . . 
. . . d d 1 f f 1 f f 1 d . . . 
. . . d d 1 1 1 1 1 1 1 d . . . 
. . . f d 1 1 f f f 1 1 f . . . 
. . . f d d 1 1 f 1 1 d f . . . 
. . . f d d d d d d d d f . . . 
. . . f d 1 1 1 1 1 1 d f . . . 
. . . d d 1 f 1 f f 1 d d . . . 
. . . d d 1 1 1 1 1 1 d d . . . 
. . . d d 1 f f 1 f 1 d d . . . 
. . . . d d 1 1 1 1 d d . . . . 
. . . . f f f . . f f f . . . . 
. . . . f . f . . f . f . . . . 
`;
            case "image5":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 5 5 5 5 5 5 1 . . . . . 
. . . 5 5 5 5 f 5 5 5 1 . . . . 
. . 5 5 5 5 f f f 5 5 5 1 . . . 
. . 5 5 5 f 5 f 5 5 5 5 1 . . . 
. . 5 5 5 5 f f 5 5 5 5 1 . . . 
. . 5 5 5 5 5 f f 5 5 5 1 . . . 
. . 5 5 5 f f f 5 5 5 5 1 . . . 
. . 5 5 5 5 5 f 5 5 5 5 1 . . . 
. . 5 5 5 5 5 5 5 5 5 5 1 . . . 
. . . 5 5 5 5 5 5 5 5 1 . . . . 
. . . . 5 5 5 5 5 5 5 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":return img`
. 9 . . . . . . . . . . . . . . 
6 9 9 . . . . . . . . . . . . . 
6 9 9 . e e e . . . . . . . . . 
6 6 9 . f . e e . . . . . . . . 
. 2 . . f . . e e e . . . . . . 
. 2 . . f . . . . e e . . . . . 
. 2 . . f . . . . . e e . . . . 
. 2 . . f . . . . . . e . . . . 
. 2 . . f . . . . . . e . . . . 
. 2 . . f . . . . . e e . . . . 
. 2 . . f . . . . e e . . . . . 
. 2 . . f . . e e e . . . . . . 
. 2 . . f . e e . . . . . . . . 
. 2 . . e e e . . . . . . . . . 
. 2 . . . . . . . . . . . . . . 
. 2 . . . . . . . . . . . . . . 
`;
            case "image7":return img`
. . . . . . . . . . . . . . . . 
. . . 1 1 1 1 1 1 1 1 1 1 . . . 
. . 1 1 1 1 1 1 1 1 1 1 1 1 . . 
. 1 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
. 1 1 f f f 1 1 1 f f f 1 1 1 . 
. 1 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
. 1 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
. 1 1 1 1 1 f f f f 1 1 1 1 1 . 
. 1 1 1 1 f f f f f f 1 1 1 1 . 
. 1 1 1 1 f f f f f f 1 1 1 1 . 
. 1 1 1 1 f f f f f f 1 1 1 1 . 
. 1 1 1 1 1 f f f f 1 1 1 1 1 . 
. 1 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
. 1 1 1 1 1 1 1 1 1 1 1 1 1 1 . 
. 1 . 1 . 1 . 1 . 1 . 1 . . 1 . 
. 1 . 1 . 1 . 1 . 1 . 1 . . 1 . 
`;
            case "image8":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . 5 . . 1 
. . . . . . . . . . . 5 5 . 1 1 
. 2 2 2 2 2 2 2 2 2 2 5 5 1 1 1 
d 2 2 2 2 2 2 2 2 2 2 5 5 1 1 1 
. 2 2 2 2 2 2 2 2 2 2 5 5 1 1 1 
. . . . . . . . . . . 5 5 . 1 1 
. . . . . . . . . . . . 5 . . 1 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image9":return img`
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
.............................fffffffffff........................................
...........................fffffffffffffff..f...................................
.....................ffffffffdddddddddddfff.f...................................
..................fffffffffddddddddddddddfffff..................................
................ffff.ffffddddddddddddddddddfffff................................
................f.f.fffddddddddddddddddddddddffffffffff.........................
...............f.ffffdddddddddddddddddddddddddffff.....ff.......................
...............f.fffdddddddddddddddddddddddddddffff......f......................
...............ffffddddddddddddddddddddddddddddfffffff....f.....................
..............ffffddddddddddddddddddddddddddddddf.ff..ff..ff....................
............ff.ffddddddddddddddddddddfffffdddddddffff..f...f....................
...........f.fffddddfffffddddddddddddfef1fddddddddffff..ff.f....................
..........f.ffffddddf1fefddddddddddddfefffdddddddddf.ff...ff....................
..........f.fffdddddffeefddddddddddddfeeffddddddddddffff...f....................
..........fffffddddffeeefddddddddddddfffffddddddddddf.fff..fff..................
..........ffffdddddffffffddddddddddddddddddddddddddddf.fff..ff..................
..........ffffdddddddddddddddddddddddddddddddddddddddf..ffffff..................
..........ff.fdddddddddddddddddddddddddddddddddddddddf..f.ffffff................
.........fffffddddddddddddddddddfdffdddddddddddddddddf..fffffffff...............
........ff.fffddddddddddddddddddfdfddddddddddddddddddf.......fffff..............
.......fff.f.fddddddddddddddddddfdfddddddddddddddddddf.........ff...............
...fffffff.f.fdddddddddddddddddfddfddddddddddddddddddf.........f.f..............
.......ff.ff.fddddddddfffdddddffddfdddddddddfffddddddf..........f.ff............
...ffff.ff...fddddddddf2ffdddffddddfddddddddffdddddddf..........f..ff...........
...fffff.....fddddddddff2ffddddddddffdddddddffdddddddf..........ffff............
......ff.....fdddddddddf22ffddddddddddddddddffdddddddf..........................
.............fdddddddddf222fffddddddddddddddffdddddddf..........................
.............fdddddddddff2222fffdddddddddddfffdddddddf..........................
..............fdddddddddff22222fffdddddddff2ffddddddf...........................
..............fddddddddddffff22222ffffdff222fdddddddf........ff..f..............
......ff.......fddddddddddddfff222222fff222ffddddddf......fffff.ff..............
.....ffffff....fddddddddddddddfff2222222222fdddddddf....fffdfdffddf.............
.....fdffdff....fddddddddddddddddfffffffffffddddddf.....fdfffdfddff.............
....ffdfdffff...fdddddddddddddddddddddddddddddddddf.....fdfffffddf..............
...fdfdfffddf....fdddddddddddddddddddddddddddddddf......fdffffddfff.............
...fdfdfffdfff....fdddddddddddddddddddddddddddddf.......fddddfddfdff............
...fdfdddfffdf.....fdddddddddddddddddddddddddddf........fddddddddddf............
..ffffdddddddf......fdddddddddddddddddddddddddf..........fffdddddddf............
..fdfdddddddff.......ffdddddddddddddddddddddff............fdfdddffff............
..fdfddddffff..........ffdddddddddddddddddff.............fdddffff...............
..fffdddfdf..............ffdddddddddddddff..............fddddff.................
...fddddfddf...............fffffffffffff................fddddf..................
....ffffdddf..............fdddddddddddddf..............fddddf...................
.......fddddf.............fdddddddddddddf.............fddddf....................
........fddddf............fdddddddddddddf............fdddddf....................
.........fddddf..........fdddddddddddddddf..........fdddddf.....................
.........fddddf..........fdddddddddddddddf..........fddddf......................
..........fddddf.........fddddddddddddddddf........fdddddf......................
...........fddddf.......fdddddddddddddddddf.......fdddddf.......................
............fdddf.......fddddddddddddddddddf.....fdddddf........................
.............fdddf......fddddddddddddddddddf....fddddddf........................
.............fddddf....fddddddddddddddddddddf..fddddddf.........................
..............fddddf...fddddddddddddddddddddf..fdddddf..........................
...............fdddf..fddddddddddddddddddddddffddddddf..........................
................fdddf.fddddddddddddddddddddddfddddddf...........................
.................fdddffdddddddddddddddddddddddfddddf............................
.................fdddfddddddddddddddddddddddddfddddf............................
..................fddfdddddddddddddddddddddddddfddf.............................
...................fdfdddddddddddddddddddddddddfdf..............................
....................fddddddddddddddddddddddddddfdf..............................
....................fdddddddddddddddddddddddddddf...............................
....................fdddddddddddddddddddddddddddf...............................
...................fdddddddddddddddddddddddddddddf..............................
...................fdddddddddddddddddddddddddddddf..............................
...................fddddddddddddddddddddddddddddddf.............................
..................fdddddddddddddddddddddddddddddddf.............................
..................fddddddddddddddddddddddddddddddddf............................
..................fddddddddddddddddddddddddddddddddf............................
.................fddddddddddddddddddddddddddddddddddf...........................
.................fddddddddddddddddddddddddddddddddddf...........................
................fddddddddddddddddddddddddddddddddddddf..........................
................fddddddddddddddddddddddddddddddddddddf..........................
................fdddddddddddddddddddddddddddddddddddddf.........................
...............fddddddddddddddddddddddddddddddddddddddf.........................
...............fdddddddddddddddddddddddddddddddddddddddf........................
...............fdddddddddddddddddddfffffffffffffffffffff........................
..............fffffffffffffffffffff......fddf...................................
.....................fdf..................fddf..................................
.....................fdf..................fddf..................................
.....................fdf...................fddf.................................
....................fdf....................fdddf................................
....................fdf.....................fddf................................
...................fdf.......................fddf...............................
...................fdf.......................fddf...............................
...................fdf........................fddf..............................
..................fdf.........................fddf..............................
..................fdf..........................fddf.............................
..................fdf..........................fddf.............................
.................fdf............................fddf............................
.................fdf............................fddf............................
................fddf.............................fddf...........................
................fdf..............................fdddf..........................
................fdf...............................fddf..........................
...............fdf.................................fddf.........................
...............fdf.................................fddf.........................
..............fddf..................................fdffffffff..................
..............fdf...................................ffffddddff..................
..............fdf....................................fddddddf...................
........fffffffdf....................................ffdddddf...................
........fdddddfff.....................................fffffff...................
........fddddddf................................................................
........fddddddf................................................................
........fffffddf................................................................
............ffff................................................................
................................................................................
................................................................................
................................................................................
`;
            case "image11":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. f . . . . . . . . . . . . f . 
. . f . . . . . . . . . . f . . 
. . . f . . . . . . . . f . . . 
. . . . f . . . . . . f . . . . 
. . . . . f f f f f f . . . . . 
. . . . . . . 7 7 . . . . . . . 
. . . . . . . 7 7 . . . . . . . 
. . . . . . . 7 7 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image13":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. f . . . . . . . . . . . . f . 
. . f . . . . . . . . . . f . . 
. . . f . . . . . . . . f . . . 
. . . . f . . . . . . f . . . . 
. . . . . f f f f f f . . . . . 
. . . . . . . 5 5 . . . . . . . 
. . . . . . . 5 5 . . . . . . . 
. . . . . . . 5 5 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . d d f f f f d d . . . . 
. . . d d d d d d d d d d . . . 
. . . d d 1 1 1 d 1 1 1 d . . . 
. . . d d 1 f f 1 f f 1 d . . . 
. . . d d 1 1 1 1 1 1 1 d . . . 
. . . f d 1 1 f f f 1 1 f . . . 
. . . f d d 1 1 f 1 1 d f . . . 
. . . f d d d d d d d d f . . . 
. . . f d 1 1 1 1 1 1 d f . . . 
. . . d d 1 f 1 f f 1 d d . . . 
. . . d d 1 1 1 1 1 1 d d . . . 
. . . d d 1 f f 1 f 1 d d . . . 
. . . . d d 1 1 1 1 d d . . . . 
. . . . f f f . . f f f . . . . 
. . . . . . f . . f . f . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . d d f f f f d d . . . . 
. . . d d d d d d d d d d . . . 
. . . d d 1 1 1 d 1 1 1 d . . . 
. . . d d 1 f f 1 f f 1 d . . . 
. . . d d 1 1 1 1 1 1 1 d . . . 
. . . f d 1 1 f f f 1 1 f . . . 
. . . f d d 1 1 f 1 1 d f . . . 
. . . f d d d d d d d d f . . . 
. . . f d 1 1 1 1 1 1 d f . . . 
. . . d d 1 f 1 f f 1 d d . . . 
. . . d d 1 1 1 1 1 1 d d . . . 
. . . d d 1 f f 1 f 1 d d . . . 
. . . . d d 1 1 1 1 d d . . . . 
. . . . f f f . . f f f . . . . 
. . . . f . f . . f . . . . . . 
`];
            case "anim2":return [img`
. . . . . . . . . . . . . . . . 
. . . . d d f f f f d d . . . . 
. . . d d d d d d d d d d . . . 
. . . d d 1 1 1 d 1 1 1 d . . . 
. . . d d 1 f f 1 f f 1 d . . . 
. . . d d 1 1 1 1 1 1 1 d . . . 
. . . f d 1 1 f f f 1 1 f . . . 
. . . f d d 1 1 f 1 1 d f . . . 
. . . f d d d d d d d d f . . . 
. . . f d 1 1 1 1 1 1 d f . . . 
. . . d d 1 f 1 f f 1 d d . . . 
. . . d d 1 1 1 1 1 1 d d . . . 
. . . d d 1 f f 1 f 1 d d . . . 
. . . . d d 1 1 1 1 d d . . . . 
. . . . f f f . . f f f . . . . 
. . . . . . f . . f . f . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . d d f f f f d d . . . . 
. . . d d d d d d d d d d . . . 
. . . d d 1 1 1 d 1 1 1 d . . . 
. . . d d 1 f f 1 f f 1 d . . . 
. . . d d 1 1 1 1 1 1 1 d . . . 
. . . f d 1 1 f f f 1 1 f . . . 
. . . f d d 1 1 f 1 1 d f . . . 
. . . f d d d d d d d d f . . . 
. . . f d 1 1 1 1 1 1 d f . . . 
. . . d d 1 f 1 f f 1 d d . . . 
. . . d d 1 1 1 1 1 1 d d . . . 
. . . d d 1 f f 1 f 1 d d . . . 
. . . . d d 1 1 1 1 d d . . . . 
. . . . f f f . . f f f . . . . 
. . . . f . f . . f . . . . . . 
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
